config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
 root "dashboards#show"
  devise_for :admins, controllers: { sessions: 'admin/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:show, :edit, :update] do
    resources :recommended_posts, only: [:index]
  end

  resources :posts, except: [:index] do
    resources :responses, only: [:create]
  end

  resources :tags, only: [:show]

  get "me/Capsule" => "dashboards#bookmarks", as: :dashboard_bookmarks
  get "top-Posts" => "dashboards#top_stories", as: :top_stories
  get "me/stories/drafts" => "stories#drafts", as: :stories_drafts
  get "me/stories/public" => "stories#published", as: :stories_published
  get "search" => "search#show", as: :search
  get "search/users" => "search#users", as: :search_users
  post "posts/create_and_edit" => "posts#create_and_edit", as: :post_create_and_edit

  namespace :admin do
    resource :dashboard, only: [:show]
    resources :featured_tags, only: [:create, :destroy]
    resources :featured_posts, only: [:create, :destroy]
  end

  namespace :api do
    resources :notifications, only: [:index] do
      post :mark_as_touched, on: :collection
      post :mark_all_as_read, on: :collection
      post :mark_as_read, on: :member
    end

    get "autocomplete" => "search_autocomplete#index"

    resources :posts, only: [:create, :update, :destroy]
    resources :users, only: [:show]
    resources :likers, only: [:index]
    resources :tag_followers, only: [:index]
    resources :followers, only: [:index]
    resources :following, only: [:index]
    resources :following_tags, only: [:index]
    resources :tags, only: [:create]
    resources :follow_suggestions, only: [:index]

    resources :posts, only: [] do
      resource :likes, only: [:create, :destroy], module: :posts
      resource :bookmarks, only: [:create, :destroy], module: :posts
    end

    resources :responses, only: [] do
      resource :likes, only: [:create, :destroy], module: :responses
      resource :bookmarks, only: [:create, :destroy], module: :responses
    end

    post    "relationships" => "relationships#create"
    delete  "relationships" => "relationships#destroy"
    post    "interests" => "interests#create"
    delete  "interests" => "interests#destroy"
  end

  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq' 
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :beautify_url
  layout "simple"

  def show
    @post_records = Post.search(query_term).paginate(page: params[:page]).records
    @posts = @post_records.to_a.select { |post| post.published? }
    @users = User.search(query_term).records.to_a
    @tags = Tag.search(query_term).records
  end

  def users
    @users = User.search(query_term).records.to_a
  end

  private

    def beautify_url
      if params[:search].present?
        case params[:action]
        when "show"
          redirect_to search_url(q: params[:search][:q])
        when "users"
          redirect_to search_users_url(q: params[:search][:q])
        end
      end
    end

    def query_term
      params[:q] || ''
    end
end

app/views/search/_user_card.html.erb
<div class="user-card">
  <div class="avatar-wrapper">
    <%= avatar_for user, size: 50 %>
  </div>
  <div class="uc-metadata">
    <h4><%= link_to user.username, user %></h4>
    <p><%= user.description %></p>
    <%= follow_button_for(user) %>
  </div>
</div>

app/views/search/show.html.erb
<div class="col-xs-10 col-xs-offset-1">
  <div class="row">
    <div class="col-md-12 large-searchbar">
      <%= form_for :search, url: search_path, method: :get do |f| %>
        <%= f.search_field :q, value: params[:q], placeholder: 'Search Prattsule', autofocus: true, autocomplete: 'off', onfocus: "this.value = this.value;" %>
      <% end %>
    </div>
  </div>


  <div class="row">
    <div class="col-md-2">
      <div class="search-filter-links">
        <div class="active filter-link">
          <%= link_to search_path(q: params[:q]) do %>
            All <span class="glyphicon glyphicon-chevron-right pull-right"></span>
          <% end %>
        </div>
        <div class="filter-link"><%= link_to 'People', search_users_path(q: params[:q]) %></div>
      </div>
    </div>

    <div class="col-md-6" data-animation="fadeInUp-fadeOutDown">
      <% if @posts.any? %>
        <div data-behavior="endless-scroll">
          <h4 class="small-heading border-top">Posts</h4>
          <%= render @posts %>
        </div>
        <div class="center">
          <%= will_paginate @post_records %>
        </div>
      <% end %>
    </div>

    <aside class="col-md-4" data-animation="fadeInUp-fadeOutDown">
      <% if @tags.any? %>
        <h4 class="small-heading border-top">Tags</h4>
        <%= react_component('TagList', { tags: @tags }, { prerender: true }) %>
      <% end %>
      <% if @users.any? %>
        <h4 class="small-heading border-top">People</h4>
        <% @users.each do |user| %>
          <%= render partial: 'search/user_card', locals: { user: user } %>
        <% end %>
      <% end %>
    </aside>

  </div>
</div>

app/views/search/show.js.erb
$('[data-behavior="endless-scroll"]').append('<%= j render @posts %>');

ReactRailsUJS.mountComponents();

<% if @post_records.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @post_records %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/search/users.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="row">
    <div class="col-md-12 large-searchbar">
      <%= form_for :search, url: search_users_path, method: :get do |f| %>
        <%= f.search_field :q, value: params[:q], placeholder: 'Search Prattsule', autofocus: true, autocomplete: 'off', onfocus: "this.value = this.value;" %>
      <% end %>
    </div>
  </div>


  <div class="row">
    <div class="col-md-2">
      <div class="search-filter-links">
        <div class="filter-link"><%= link_to 'All', search_path(q: params[:q]) %></div>
        <div class="active filter-link">
          <%= link_to search_users_path(q: params[:q]) do %>
            People <span class="glyphicon glyphicon-chevron-right pull-right"></span>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-7" data-animation="fadeInUp-fadeOutDown">
      <div>
        <% @users.each do |user| %>
          <div class="user-panel">
            <div class="avatar-wrapper">
              <%= avatar_for user, size: 60 %>
            </div>
            <div class="user-metadata">
              <h4><%= link_to user.username, user %></h4>
              <p><%= user.description %></p>
            </div>
            <div class="follow-button-wrapper">
              <%= follow_button_for(user) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>