config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
 root "dashboards#show"
  devise_for :admins, controllers: { sessions: 'admin/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:show, :edit, :update] do
    resources :recommended_posts, only: [:index]
  end

  resources :posts, except: [:index] do
    resources :responses, only: [:create]
  end

  resources :tags, only: [:show]

  get "me/Capsule" => "dashboards#bookmarks", as: :dashboard_bookmarks
  get "top-Posts" => "dashboards#top_stories", as: :top_stories
  get "me/stories/drafts" => "stories#drafts", as: :stories_drafts
  get "me/stories/public" => "stories#published", as: :stories_published
  get "search" => "search#show", as: :search
  get "search/users" => "search#users", as: :search_users
  post "posts/create_and_edit" => "posts#create_and_edit", as: :post_create_and_edit

  namespace :admin do
    resource :dashboard, only: [:show]
    resources :featured_tags, only: [:create, :destroy]
    resources :featured_posts, only: [:create, :destroy]
  end

  namespace :api do
    resources :notifications, only: [:index] do
      post :mark_as_touched, on: :collection
      post :mark_all_as_read, on: :collection
      post :mark_as_read, on: :member
    end

    get "autocomplete" => "search_autocomplete#index"

    resources :posts, only: [:create, :update, :destroy]
    resources :users, only: [:show]
    resources :likers, only: [:index]
    resources :tag_followers, only: [:index]
    resources :followers, only: [:index]
    resources :following, only: [:index]
    resources :following_tags, only: [:index]
    resources :tags, only: [:create]
    resources :follow_suggestions, only: [:index]

    resources :posts, only: [] do
      resource :likes, only: [:create, :destroy], module: :posts
      resource :bookmarks, only: [:create, :destroy], module: :posts
    end

    resources :responses, only: [] do
      resource :likes, only: [:create, :destroy], module: :responses
      resource :bookmarks, only: [:create, :destroy], module: :responses
    end

    post    "relationships" => "relationships#create"
    delete  "relationships" => "relationships#destroy"
    post    "interests" => "interests#create"
    delete  "interests" => "interests#destroy"
  end

  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq' 
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!

  def drafts
    @drafts = current_user.posts.recent.drafts
  end

  def published
    @posts = current_user.posts.recent.published
  end
end

app/views/stories/drafts.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="side-padding-5">
      <header class="hero flex-container flex-space-btw">
        <h1 class="hero-title">Your posts</h1>
        <div class="button-set">
          <%= link_to "Write a story", new_post_path, class: "button green-border-button" %>
        </div>
      </header>

      <nav class="nav-tabs">
        <ul>
          <li><%= nav_link_to "Drafts", stories_drafts_path %></li>
          <li><%= nav_link_to "Public", stories_published_path %></li>
        </ul>
      </nav>

      <div data-animation="fadeInUp-fadeOutDown">
        <% if @drafts.any? %>
          <% @drafts.each do |draft| %>
            <div class="story-card" id="story_<%= draft.id %>">
              <strong class="sc-title"><%= link_to (draft.title || "Untitled"), edit_post_path(draft) %></strong>
              <small class="sc-metadata">
                Last edited <%= time_ago_in_words(draft.updated_at) %> ago &#149; 
                <% if draft.body.present? %>
                  <%= post_length_in_minutes(draft.body) %> 
                  (<%= pluralize(draft.word_count, 'word') %>) so far &#149;
                <% end %>
                <div class="btn-group">
                  <button type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-chevron-down"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Edit", edit_post_path(draft) %></li>
                    <li><%= link_to "Delete", api_post_path(draft), method: :delete, remote: true %></li>
                  </ul>
                </div>
              </small>
            </div>
          <% end %>
        <% else %>
          <p class="no-sc-message">No drafts yet</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/stories/published.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="side-padding-5">
      <header class="hero flex-container flex-space-btw">
        <h1 class="hero-title">Your posts</h1>
        <div class="button-set">
          <%= link_to "Write a post", new_post_path, class: "button green-border-button" %>
        </div>
      </header>

      <nav class="nav-tabs">
        <ul>
          <li><%= nav_link_to "Drafts", stories_drafts_path %></li>
          <li><%= nav_link_to "Public", stories_published_path %></li>
        </ul>
      </nav>

      <div data-animation="fadeInUp-fadeOutDown">
        <% if @posts.any? %>
          <% @posts.each do |post| %>
            <div class="story-card" id="story_<%= post.id %>">
              <strong class="sc-title"><%= link_to post.title, edit_post_path(post) %></strong>
              <small class="sc-metadata">Published <%= time_ago_in_words(post.published_at) %> ago &#149; <%= post_length_in_minutes(post.body) %>
                <div class="btn-group">
                  <button type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-chevron-down"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Edit", edit_post_path(post) %></li>
                    <li><%= link_to "Delete", api_post_path(post), method: :delete, remote: true %></li>
                  </ul>
                </div>
              </small>
            </div>
          <% end %>
        <% else %>
          <p class="no-sc-message">No published posts yet</p>
        <% end %>
      </div>
    </div>
  </div>
</div>