config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
 root "dashboards#show"
  devise_for :admins, controllers: { sessions: 'admin/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:show, :edit, :update] do
    resources :recommended_posts, only: [:index]
  end

  resources :posts, except: [:index] do
    resources :responses, only: [:create]
  end

  resources :tags, only: [:show]

  get "me/Capsule" => "dashboards#bookmarks", as: :dashboard_bookmarks
  get "top-Posts" => "dashboards#top_stories", as: :top_stories
  get "me/stories/drafts" => "stories#drafts", as: :stories_drafts
  get "me/stories/public" => "stories#published", as: :stories_published
  get "search" => "search#show", as: :search
  get "search/users" => "search#users", as: :search_users
  post "posts/create_and_edit" => "posts#create_and_edit", as: :post_create_and_edit

  namespace :admin do
    resource :dashboard, only: [:show]
    resources :featured_tags, only: [:create, :destroy]
    resources :featured_posts, only: [:create, :destroy]
  end

  namespace :api do
    resources :notifications, only: [:index] do
      post :mark_as_touched, on: :collection
      post :mark_all_as_read, on: :collection
      post :mark_as_read, on: :member
    end

    get "autocomplete" => "search_autocomplete#index"

    resources :posts, only: [:create, :update, :destroy]
    resources :users, only: [:show]
    resources :likers, only: [:index]
    resources :tag_followers, only: [:index]
    resources :followers, only: [:index]
    resources :following, only: [:index]
    resources :following_tags, only: [:index]
    resources :tags, only: [:create]
    resources :follow_suggestions, only: [:index]

    resources :posts, only: [] do
      resource :likes, only: [:create, :destroy], module: :posts
      resource :bookmarks, only: [:create, :destroy], module: :posts
    end

    resources :responses, only: [] do
      resource :likes, only: [:create, :destroy], module: :responses
      resource :bookmarks, only: [:create, :destroy], module: :responses
    end

    post    "relationships" => "relationships#create"
    delete  "relationships" => "relationships#destroy"
    post    "interests" => "interests#create"
    delete  "interests" => "interests#destroy"
  end

  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq' 
  end
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id             :integer          not null, primary key
#  name           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  featured       :boolean          default("false")
#  slug           :string
#  lowercase_name :string
#

class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings

  has_many :interests, dependent: :destroy
  has_many :followers, through: :interests, source: :follower

  has_many :tag_relationships, -> { order(relevance: :desc) }, dependent: :destroy
  has_many :related_tags, through: :tag_relationships, source: :related_tag

  validates :name, presence: true

  include SearchableTag

  extend FriendlyId
  friendly_id :name, use: [ :slugged, :finders ]

  def self.first_or_create_with_name!(name)
    where(lowercase_name: name.strip.downcase).first_or_create! do |tag|
      tag.name = name.strip
    end
  end
end

app/controllers/api/tags_controller.rb
class API::TagsController < ApplicationController
  before_action :authenticate_user!

  def create
    if params[:tag_name].strip.present?
      tag = Tag.first_or_create_with_name!(params[:tag_name])
      current_user.following_tags << tag unless current_user.following_tag?(tag)
    end
    render json: tag.to_json, status: 200
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag
  def show
    @dashboard = Dashboard.new(user: current_user, posts: tagged_posts, tag: @tag)
    @related_tags = @tag.related_tags
  end

  private

    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tagged_posts
      @_tagged_posts ||= Post.tagged_with(@tag.name).published.includes(:user).paginate(page: params[:page])
    end
end

app/views/tags/_tag.html.erb
<%= link_to tag.name, tag, class: 'tag' %>

app/views/tags/show.html.erb
<div class="col-md-6 col-md-offset-1 dashboard-main-content">

  <div data-animation="fadeInUp-fadeOutDown">
    <div class="heading-container">
      <% if admin_signed_in? %>
        <%= feature_tag_button_for(@dashboard.tag) %>
      <% else %>
        <%= follow_tag_button_for(@dashboard.tag) %>
      <% end %>
      <small class="heading-prefix">Tagged in</small>
      <h3 class="heading-title"><%= @dashboard.tag.name %></h3>

    </div>

    <div class="tag-followers-list">
      <small class="heading-prefix">People Interested in <%= @dashboard.tag.name %></small>
      <%= react_component('TagFollowersList', { tagId: @dashboard.tag.id }) %>
    </div>
  </div>

  <div class="posts-wrapper" data-behavior="endless-scroll" data-animation="fadeInUp-fadeOutDown">
    <%= render @dashboard.posts %>
  </div>

  <%= will_paginate @dashboard.posts %>

</div>

<% content_for :sidebar do %>
  <aside class="col-md-4 main-sidebar">
    <% if @related_tags.any? %>
      <h4 class="small-heading border-top">Related Tags</h4>
      <%= react_component('TagList', { tags: @related_tags }) %>
    <% end %>

    <% if user_signed_in? %>
      <div class="flex-container border-top">
        <h4 class="small-heading">Tags you follow</h4>
        <%= react_component('AddTagButton') %>
      </div>
      <%= react_component('FollowingTagList', { followingTags: current_user.following_tags }) %>
    <% end %>

    <% unless @dashboard.filtered? %>
      <h4 class="small-heading border-top">Top stories</h4>
      <div class="sidebar-top-stories">
        <ul>
          <% @dashboard.top_stories.each_with_index do |post, index| %>
            <li class="top-stories-list-item">
              <div class="count-button-wrapper">
                <span class="count-button"><%= index + 1 %></span>
              </div>
              <div class="top-stories-links">
                <%= link_to post.title, post, class: 'post-title' %><br/>
                <small>
                  <%= react_component("PopoverLink", { user_id: post.user.id, url: user_path(post.user), children: post.username }) %>
                </small>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </aside>
<% end %>

app/views/tags/show.js.erb
$('[data-behavior="endless-scroll"]').append('<%= j render @dashboard.posts %>');

ReactRailsUJS.mountComponents();

<% if @dashboard.posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @dashboard.posts %>');
<% else %>
  $('.pagination').remove();
<% end %>